services:
  document-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-document:/var/opt/mssql
  occurrence-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-occurrence:/var/opt/mssql
  short-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-short:/var/opt/mssql
  medium-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-medium:/var/opt/mssql
  long-word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data-long:/var/opt/mssql
  wordservice:
    build: 
      context: .
      dockerfile: WordService/Dockerfile
    deploy:
      replicas: 3
    hostname: wordservice
    depends_on:
      - document-db
      - occurrence-db
      - short-word-db
      - medium-word-db
      - long-word-db
  nginx:
    depends_on:
      - wordservice
    image: nginx:latest
    ports:
      - "8080:80"
    entrypoint: >
      sh -c "
      echo '
      events { }

      http {
          upstream web_backend {
              server wordservice:5064;
              server wordservice:5064;
              server wordservice:5064;
          }

          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass http://web_backend;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Real-IP $$remote_addr;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $$scheme;
              }
          }
      }
      ' > /etc/nginx/nginx.conf &&
      cat /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'
      "

volumes:
  mssql-document:
  mssql-occurrence:
  mssql-data-short:
  mssql-data-medium:
  mssql-data-long: